/** Canonical sidebar strategy tree — single source for catalog stubs and route resolution. */
export interface SidebarStrategyGroup {
  slug: string;
  label: string;
  strategies: string[];
}

export function strategySlug(label: string): string {
  return label
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export const SIDEBAR_STRATEGY_GROUPS: SidebarStrategyGroup[] = [
  {
    slug: 'trend-following-strategies',
    label: 'Trend Following Strategies',
    strategies: [
      'Moving Average Crossover',
      'EMA Pullback Strategy',
      'Trendline Breakout',
      'Higher Highs & Higher Lows',
      'MACD Trend Strategy',
      'SuperTrend Strategy',
      'ADX Trend Strategy',
      'Ichimoku Trend Strategy',
      '200 EMA Trend Strategy',
      'Multi-Timeframe Trend Confirmation',
      'Trend Continuation Pattern Strategy',
      'Dynamic Support & Resistance Trend Trading',
      'Fibonacci Trend Continuation',
      'Channel Trend Trading',
      'Trend Acceleration Strategy',
      'Institutional Trend Following',
    ],
  },
  {
    slug: 'breakout-trading-strategies',
    label: 'Breakout Trading Strategies',
    strategies: [
      'London Breakout',
      'Asian Session Breakout',
      'New York Breakout',
      'Opening Range Breakout (ORB)',
      'Daily High/Low Breakout',
      'Weekly Breakout',
      'Triangle Breakout',
      'Rectangle Breakout',
      'Volatility Breakout',
      'News Breakout',
      'Bollinger Band Squeeze Breakout',
      'Range Expansion Breakout',
      'Liquidity Breakout',
      'Fake Breakout Reversal',
      'Consolidation Breakout',
    ],
  },
  {
    slug: 'scalping-strategies',
    label: 'Scalping Strategies',
    strategies: [
      '1-Minute Scalping',
      '5-Minute Scalping',
      'Tick Scalping',
      'Spread Scalping',
      'Order Flow Scalping',
      'DOM Scalping',
      'Momentum Scalping',
      'EMA Scalping',
      'VWAP Scalping',
      'RSI Scalping',
      'Stochastic Scalping',
      'Price Action Scalping',
      'Liquidity Grab Scalping',
      'News Scalping',
      'Session Scalping',
      'High Frequency Scalping',
      'Algorithmic Scalping',
    ],
  },
  {
    slug: 'day-trading-strategies',
    label: 'Day Trading Strategies',
    strategies: [
      'Intraday Trend Trading',
      'Intraday Breakout',
      'Momentum Day Trading',
      'VWAP Day Trading',
      'Opening Session Trading',
      'Mean Reversion Day Trading',
      'Gap Trading',
      'Reversal Day Trading',
      'News-Based Day Trading',
      'Correlation Day Trading',
      'Pivot Point Day Trading',
      'Range Day Trading',
      'Smart Money Day Trading',
    ],
  },
  {
    slug: 'swing-trading-strategies',
    label: 'Swing Trading Strategies',
    strategies: [
      'Swing Pullback Strategy',
      'Fibonacci Swing Trading',
      'Swing Reversal Strategy',
      'Trend Swing Trading',
      'Channel Swing Trading',
      'Harmonic Swing Trading',
      'Elliott Wave Swing Trading',
      'MACD Swing Trading',
      'RSI Swing Trading',
      'Support & Resistance Swing Trading',
      'Candlestick Swing Trading',
      'Weekly Swing Trading',
      'Position Swing Trading',
    ],
  },
  {
    slug: 'position-trading-strategies',
    label: 'Position Trading Strategies',
    strategies: [
      'Macro Trend Trading',
      'Fundamental Position Trading',
      'Carry Trade Strategy',
      'Long-Term Trend Following',
      'Economic Cycle Trading',
      'Central Bank Policy Trading',
      'Interest Rate Differential Strategy',
      'Inflation-Based Position Trading',
      'Commodity Currency Position Trading',
    ],
  },
  {
    slug: 'price-action-strategies',
    label: 'Price Action Strategies',
    strategies: [
      'Support & Resistance',
      'Supply & Demand',
      'Candlestick Trading',
      'Engulfing Pattern',
      'Pin Bar Strategy',
      'Inside Bar Strategy',
      'Fakey Pattern',
      'Break and Retest',
      'Market Structure Trading',
      'Liquidity Sweep Strategy',
      'Mitigation Block Strategy',
      'Breaker Block Strategy',
      'Fair Value Gap (FVG)',
      'Institutional Candle Trading',
      'ICT Trading Strategy',
      'BOS (Break of Structure)',
      'CHOCH (Change of Character)',
    ],
  },
  {
    slug: 'indicator-based-strategies',
    label: 'Indicator-Based Strategies',
    strategies: [
      'RSI Strategy',
      'MACD Strategy',
      'Bollinger Bands Strategy',
      'Stochastic Strategy',
      'ATR Strategy',
      'ADX Strategy',
      'CCI Strategy',
      'Parabolic SAR Strategy',
      'Ichimoku Strategy',
      'Moving Average Strategy',
      'Keltner Channel Strategy',
      'Donchian Channel Strategy',
      'Momentum Indicator Strategy',
      'Williams %R Strategy',
      'TDI Strategy',
      'Alligator Indicator Strategy',
    ],
  },
  {
    slug: 'mean-reversion-strategies',
    label: 'Mean Reversion Strategies',
    strategies: [
      'Bollinger Mean Reversion',
      'RSI Overbought/Oversold',
      'VWAP Reversion',
      'Statistical Reversion',
      'Range Reversal',
      'Channel Reversion',
      'Z-Score Reversion',
      'Deviation Reversion',
      'Reversion Scalping',
    ],
  },
  {
    slug: 'momentum-trading-strategies',
    label: 'Momentum Trading Strategies',
    strategies: [
      'Momentum Breakout',
      'Volume Momentum',
      'News Momentum',
      'MACD Momentum',
      'RSI Momentum',
      'Volatility Momentum',
      'Currency Strength Momentum',
      'Relative Strength Momentum',
    ],
  },
  {
    slug: 'reversal-trading-strategies',
    label: 'Reversal Trading Strategies',
    strategies: [
      'Double Top / Bottom',
      'Head and Shoulders',
      'RSI Divergence',
      'MACD Divergence',
      'Exhaustion Reversal',
      'Climactic Reversal',
      'Trendline Reversal',
      'Fibonacci Reversal',
      'Harmonic Reversal',
      'Supply/Demand Reversal',
      'V-Reversal',
      'Countertrend Trading',
    ],
  },
  {
    slug: 'range-trading-strategies',
    label: 'Range Trading Strategies',
    strategies: [
      'Horizontal Range Trading',
      'Bollinger Range Strategy',
      'Oscillator Range Trading',
      'Channel Trading',
      'Support & Resistance Range',
      'Asian Session Range Trading',
      'Mean Reversion Range',
      'VWAP Range Trading',
    ],
  },
  {
    slug: 'smart-money-and-institutional-strategies',
    label: 'Smart Money & Institutional Strategies',
    strategies: [
      'Smart Money Concepts (SMC)',
      'ICT Methodology',
      'Order Flow Trading',
      'Footprint Trading',
      'Liquidity Trading',
      'Order Block Trading',
      'Market Maker Model',
      'Wyckoff Method',
      'Accumulation/Distribution',
      'Manipulation-Distribution',
      'Liquidity Grab Strategy',
      'Stop Hunt Strategy',
      'Institutional Candle Model',
      'Premium & Discount Zones',
      'SMT Divergence',
      'Kill Zones',
      'Judas Swing',
      'Power of 3 (PO3)',
    ],
  },
  {
    slug: 'quantitative-and-algorithmic-strategies',
    label: 'Quantitative & Algorithmic Strategies',
    strategies: [
      'Algorithmic Trading',
      'Quantitative Trading',
      'High Frequency Trading (HFT)',
      'Statistical Arbitrage',
      'Machine Learning Trading',
      'AI-Based Trading',
      'Neural Network Trading',
      'Sentiment AI Trading',
      'Reinforcement Learning Trading',
      'Grid Algorithms',
      'Martingale Systems',
      'Anti-Martingale Systems',
      'Volatility Algorithms',
    ],
  },
  {
    slug: 'fundamental-trading-strategies',
    label: 'Fundamental Trading Strategies',
    strategies: [
      'Interest Rate Trading',
      'Central Bank Trading',
      'CPI Trading',
      'NFP Trading',
      'GDP Trading',
      'Inflation Trading',
      'Employment Data Trading',
      'Geopolitical Trading',
      'Trade Balance Trading',
      'Yield Differential Trading',
      'Monetary Policy Strategy',
      'Risk-On / Risk-Off Trading',
    ],
  },
  {
    slug: 'news-trading-strategies',
    label: 'News Trading Strategies',
    strategies: [
      'NFP Strategy',
      'FOMC Strategy',
      'CPI Strategy',
      'ECB Strategy',
      'BOE Strategy',
      'BOJ Strategy',
      'Rate Decision Trading',
      'Flash News Trading',
      'Volatility Spike Trading',
      'News Fade Strategy',
    ],
  },
  {
    slug: 'correlation-and-intermarket-strategies',
    label: 'Correlation & Intermarket Strategies',
    strategies: [
      'Currency Correlation Trading',
      'Gold-Forex Correlation',
      'Oil-CAD Correlation',
      'Bond-Yield Correlation',
      'Dollar Index (DXY) Strategy',
      'Risk Sentiment Correlation',
      'Equity-Forex Correlation',
    ],
  },
  {
    slug: 'volatility-based-strategies',
    label: 'Volatility-Based Strategies',
    strategies: [
      'ATR Breakout',
      'Volatility Compression',
      'Volatility Expansion',
      'Bollinger Squeeze',
      'Implied Volatility Trading',
      'News Volatility Strategy',
    ],
  },
  {
    slug: 'hedging-strategies',
    label: 'Hedging Strategies',
    strategies: [
      'Direct Hedge',
      'Multiple Currency Hedge',
      'Correlation Hedge',
      'Options Hedge',
      'Synthetic Hedge',
      'Partial Hedge',
    ],
  },
  {
    slug: 'arbitrage-strategies',
    label: 'Arbitrage Strategies',
    strategies: [
      'Triangular Arbitrage',
      'Latency Arbitrage',
      'Cross-Broker Arbitrage',
      'Interest Arbitrage',
      'Swap Arbitrage',
    ],
  },
  {
    slug: 'session-based-strategies',
    label: 'Session-Based Strategies',
    strategies: [
      'Asian Session Strategy',
      'London Session Strategy',
      'New York Session Strategy',
      'London-New York Overlap',
      'Tokyo Breakout',
      'Session Momentum',
      'Session Reversal',
    ],
  },
  {
    slug: 'pattern-trading-strategies',
    label: 'Pattern Trading Strategies',
    strategies: [
      'Triangle Patterns',
      'Wedge Patterns',
      'Flag Patterns',
      'Pennant Patterns',
      'Cup and Handle',
      'Harmonic Patterns',
      'Butterfly Pattern',
      'Bat Pattern',
      'Crab Pattern',
      'Gartley Pattern',
      'Cypher Pattern',
    ],
  },
  {
    slug: 'candlestick-trading-strategies',
    label: 'Candlestick Trading Strategies',
    strategies: [
      'Doji',
      'Morning Star',
      'Evening Star',
      'Hammer',
      'Shooting Star',
      'Harami',
      'Tweezer Top/Bottom',
      'Three Soldiers',
      'Three Crows',
    ],
  },
  {
    slug: 'risk-management-strategies',
    label: 'Risk Management Strategies',
    strategies: [
      'Fixed Lot Strategy',
      'Percentage Risk Model',
      'Kelly Criterion',
      'Volatility Position Sizing',
      'Dynamic Risk Allocation',
      'Equity Curve Management',
      'Portfolio Risk Balancing',
      'Drawdown Protection',
      'Daily Loss Limit Strategy',
    ],
  },
  {
    slug: 'advanced-professional-and-institutional-models',
    label: 'Advanced Professional & Institutional Models',
    strategies: [
      'Wyckoff Trading',
      'Market Profile Trading',
      'Volume Profile Trading',
      'Auction Market Theory',
      'Order Book Trading',
      'Footprint Charts',
      'Liquidity Engineering',
      'Quant Macro Trading',
      'Statistical Modeling',
      'AI Predictive Trading',
      'Neural Forecasting',
      'Institutional Flow Analysis',
      'Dark Pool Analysis',
      'Sentiment Engine Trading',
      'Cross-Asset Flow Trading',
    ],
  },
  {
    slug: 'hybrid-strategies',
    label: 'Hybrid Strategies',
    strategies: [
      'Trend + Momentum',
      'SMC + Price Action',
      'Fundamental + Technical',
      'AI + Technical Analysis',
      'News + Liquidity',
      'Scalping + Order Flow',
      'Swing + Macro Analysis',
    ],
  },
];

export function sidebarStrategyPageId(groupSlug: string, strategyLabel: string): string {
  return `${groupSlug}-${strategySlug(strategyLabel)}`;
}
