export type AccountClass='DEMO'|'LIVE'|'PROP'; export type AccountCurrency='USD'|'NGN'|string;
export type ConnectionState='DISCONNECTED'|'CONNECTING'|'AUTHENTICATING'|'SYNCHRONIZING'|'HEALTHY'|'DEGRADED'|'ERROR';
export type TradingMode='ANALYSIS_ONLY'|'APPROVAL_REQUIRED'|'AUTONOMOUS';
export interface PropRules { phase:'CHALLENGE'|'VERIFICATION'|'FUNDED'; accountSize:number; dailyLossLimitPct:number; maxLossLimitPct:number; profitTargetPct:number; minTradingDays?:number; maxTradingDays?:number; newsTrading:boolean; weekendHolding:boolean; overnightHolding:boolean; maxExposurePct:number; consistencyRulePct?:number; notes?:string; dailyLossBasis?:'ACCOUNT_SIZE'|'DAY_START'; trailingDrawdown?:boolean; maxOpenPositions?:number; maxRiskPerTradePct?:number; maxLots?:number; minRewardRisk?:number; allowedSymbols?:string[]; prohibitedWindows?:{label?:string; start:string; end:string; days?:number[]}[]; stopTradingAtTarget?:boolean }
export interface MT5Account { id:string; name:string; accountClass:AccountClass; currency:AccountCurrency; broker:string; firm?:string; server:string; login:string; terminalInstance:string; state:ConnectionState; tradingMode:TradingMode; tradingEnabled:boolean; balance:number; equity:number; margin:number; freeMargin:number; leverage:number; profit:number; connectedAt?:string; lastHeartbeat?:string; latencyMs?:number; secretRef?:string; propRules?:PropRules; riskProfile:'CONSERVATIVE'|'BALANCED'|'AGGRESSIVE'|'CUSTOM'; maxConcurrentTrades:number; assignedSymbols:string[] }
export interface SymbolMap { canonical:string; accountId:string; brokerSymbol:string; enabled:boolean; digits:number; minLot:number; maxLot:number; lotStep:number; tickSize:number; tickValue:number; spread:number; status:'MAPPED'|'UNMAPPED'|'UNAVAILABLE' }
export interface DataCoverage { accountId:string; symbol:string; timeframes:Record<string,{available:boolean; bars:number; lastBar?:string; stale?:boolean}>; lastSync:string }
export interface GatewayStats { pending:number; ordersToday:number; successful:number; rejected:number; avgExecutionMs:number; avgSlippagePips:number }
export interface RuntimeHealth { bridge:ConnectionState; marketData:'STREAMING'|'STALE'|'OFFLINE'; orderGateway:'READY'|'BLOCKED'|'DEGRADED'; heartbeat:'HEALTHY'|'STALE'|'LOST'; reconciliation:'CURRENT'|'PENDING'|'MISMATCH'; queueDepth:number; reconnectAttempts:number; lastHeartbeat:string; feedLatencyMs:number }
export interface MT5Event { id:string; timestamp:string; severity:'INFO'|'WARNING'|'ERROR'|'TRADE'|'SECURITY'; category:'CONNECTION'|'MARKET_DATA'|'ORDER'|'POSITION'|'SYSTEM'|'COMPLIANCE'; accountId?:string; symbol?:string; message:string; details?:string }
export interface Position { id:string; accountId:string; cacsmsTradeId:string; mt5OrderId:string; mt5DealId?:string; mt5PositionId:string; symbol:string; side:'BUY'|'SELL'; volume:number; entry:number; current:number; sl?:number; tp?:number; pnl:number; currency:string; status:'OPEN'|'CLOSED'|'PENDING'|'MISMATCH'; openedAt:string }
export interface MT5Snapshot { accounts:MT5Account[]; symbolMaps:SymbolMap[]; coverage:DataCoverage[]; gateway:GatewayStats; health:RuntimeHealth; events:MT5Event[]; positions:Position[]; globalTradingEnabled:boolean; updatedAt:string }
export interface MT5CommandResult {ok:boolean; message:string}
export type MT5AccountDraft = Partial<MT5Account> & { password?: string };
export interface MT5ConnectionSource { getSnapshot():Promise<MT5Snapshot>|MT5Snapshot; subscribe?(listener:(s:MT5Snapshot)=>void):()=>void; connect?(accountId:string):Promise<MT5CommandResult>; disconnect?(accountId:string):Promise<MT5CommandResult>; reconnect?(accountId:string):Promise<MT5CommandResult>; testConnection?(draft:MT5AccountDraft):Promise<MT5CommandResult>; saveAccount?(draft:MT5AccountDraft):Promise<MT5CommandResult>; setAccountTrading?(accountId:string,enabled:boolean):Promise<MT5CommandResult>; setGlobalTrading?(enabled:boolean):Promise<MT5CommandResult>; saveSymbolMap?(map:SymbolMap):Promise<MT5CommandResult>; reconcile?(accountId:string):Promise<MT5CommandResult>; emergencyStop?(scope:{accountId?:string;symbol?:string}):Promise<MT5CommandResult> }
