import {INSTRUMENTS,TIMEFRAMES} from '../data/instruments'; import type {MT5Account,MT5ConnectionSource,MT5Event,MT5Snapshot,SymbolMap} from '../types/mt5.types';
const now=()=>new Date().toISOString(); let seq=20;
const accounts:MT5Account[]=[
{id:'demo-usd',name:'Strategy Validation',accountClass:'DEMO',currency:'USD',broker:'Demo Broker',server:'Demo-MT5',login:'100001',terminalInstance:'CACSMS-MT5-0001',state:'HEALTHY',tradingMode:'AUTONOMOUS',tradingEnabled:true,balance:50000,equity:50384,margin:620,freeMargin:49764,leverage:100,profit:384,lastHeartbeat:now(),latencyMs:38,riskProfile:'BALANCED',maxConcurrentTrades:3,assignedSymbols:[...INSTRUMENTS]},
{id:'live-ngn',name:'Nigeria Live',accountClass:'LIVE',currency:'NGN',broker:'Nigeria Broker',server:'Live-NGN',login:'200002',terminalInstance:'CACSMS-MT5-0002',state:'HEALTHY',tradingMode:'APPROVAL_REQUIRED',tradingEnabled:true,balance:30000000,equity:30435000,margin:850000,freeMargin:29585000,leverage:100,profit:435000,lastHeartbeat:now(),latencyMs:51,riskProfile:'CONSERVATIVE',maxConcurrentTrades:2,assignedSymbols:[...INSTRUMENTS]},
{id:'live-usd',name:'Personal Live USD',accountClass:'LIVE',currency:'USD',broker:'Global Broker',server:'Live-01',login:'300003',terminalInstance:'CACSMS-MT5-0003',state:'HEALTHY',tradingMode:'AUTONOMOUS',tradingEnabled:true,balance:25000,equity:25242,margin:410,freeMargin:24832,leverage:200,profit:242,lastHeartbeat:now(),latencyMs:44,riskProfile:'BALANCED',maxConcurrentTrades:3,assignedSymbols:[...INSTRUMENTS]},
{id:'prop-usd',name:'Prop 100K',accountClass:'PROP',currency:'USD',broker:'Prop Broker',firm:'Example Prop Firm',server:'Funded-01',login:'400004',terminalInstance:'CACSMS-MT5-0004',state:'HEALTHY',tradingMode:'AUTONOMOUS',tradingEnabled:true,balance:100000,equity:102430,margin:1350,freeMargin:101080,leverage:100,profit:2430,lastHeartbeat:now(),latencyMs:62,riskProfile:'CONSERVATIVE',maxConcurrentTrades:2,assignedSymbols:[...INSTRUMENTS],propRules:{phase:'FUNDED',accountSize:100000,dailyLossLimitPct:5,maxLossLimitPct:10,profitTargetPct:8,minTradingDays:5,newsTrading:false,weekendHolding:false,overnightHolding:true,maxExposurePct:1,consistencyRulePct:30}}
];
const maps:SymbolMap[]=accounts.flatMap((a,ai)=>INSTRUMENTS.map((s,i)=>({canonical:s,accountId:a.id,brokerSymbol:a.id==='live-ngn'&&s==='XAUUSD'?'GOLD':a.id==='prop-usd'?s+'.pro':s,enabled:true,digits:s.includes('JPY')?3:5,minLot:.01,maxLot:100,lotStep:.01,tickSize:s==='XAUUSD'?.01:.00001,tickValue:1,spread:Number((.4+(i%7)*.15).toFixed(2)),status:'MAPPED'})));
const coverage=accounts.flatMap(a=>INSTRUMENTS.map((symbol,si)=>({accountId:a.id,symbol,timeframes:Object.fromEntries(TIMEFRAMES.map((tf,ti)=>[tf,{available:true,bars:Math.max(400,62000-Math.floor(ti*5900)-si*31),lastBar:now(),stale:false}])),lastSync:now()})));
let events:MT5Event[]=Array.from({length:18},(_,i)=>({id:'e'+i,timestamp:new Date(Date.now()-i*17000).toISOString(),severity:i%7===0?'TRADE':i%5===0?'WARNING':'INFO',category:i%7===0?'ORDER':i%5===0?'MARKET_DATA':'SYSTEM',accountId:accounts[i%accounts.length].id,symbol:INSTRUMENTS[i%INSTRUMENTS.length],message:i%7===0?'Order acknowledged and position synchronized':i%5===0?'Spread threshold observation':'Heartbeat and runtime synchronization healthy'}));
let snapshot:MT5Snapshot={accounts,symbolMaps:maps,coverage,gateway:{pending:0,ordersToday:7,successful:7,rejected:0,avgExecutionMs:138,avgSlippagePips:.24},health:{bridge:'HEALTHY',marketData:'STREAMING',orderGateway:'READY',heartbeat:'HEALTHY',reconciliation:'CURRENT',queueDepth:2,reconnectAttempts:0,lastHeartbeat:now(),feedLatencyMs:43},events,positions:[{id:'p1',accountId:'demo-usd',cacsmsTradeId:'CT-260926-0142',mt5OrderId:'9200142',mt5DealId:'9300142',mt5PositionId:'9400142',symbol:'EURUSD',side:'BUY',volume:.24,entry:1.17642,current:1.17711,sl:1.1729,tp:1.1834,pnl:16.56,currency:'USD',status:'OPEN',openedAt:new Date(Date.now()-3600000).toISOString()},{id:'p2',accountId:'live-ngn',cacsmsTradeId:'CT-260926-0137',mt5OrderId:'9200137',mt5PositionId:'9400137',symbol:'XAUUSD',side:'BUY',volume:.1,entry:3764.2,current:3770.8,sl:3749,tp:3798,pnl:106400,currency:'NGN',status:'OPEN',openedAt:new Date(Date.now()-7200000).toISOString()}],globalTradingEnabled:true,updatedAt:now()};
const listeners=new Set<(s:MT5Snapshot)=>void>(); const emit=()=>{snapshot={...snapshot,updatedAt:now(),health:{...snapshot.health,lastHeartbeat:now(),feedLatencyMs:35+Math.floor(Math.random()*25)},accounts:snapshot.accounts.map(a=>({...a,lastHeartbeat:now(),latencyMs:35+Math.floor(Math.random()*35)}))};listeners.forEach(x=>x(snapshot))};
let timer:any; const event=(message:string,severity:MT5Event['severity']='INFO',accountId?:string)=>{const next:MT5Event={id:'e'+(++seq),timestamp:now(),severity,category:'SYSTEM',accountId,message};events=[next,...events].slice(0,100);snapshot={...snapshot,events};emit()};
export function createDemoMT5Source():MT5ConnectionSource{return {getSnapshot:()=>snapshot,subscribe(cb){listeners.add(cb);cb(snapshot);if(!timer)timer=setInterval(emit,2000);return()=>{listeners.delete(cb);if(!listeners.size&&timer){clearInterval(timer);timer=null}}},async connect(id){snapshot={...snapshot,accounts:snapshot.accounts.map(a=>a.id===id?{...a,state:'HEALTHY'}:a)};event('Account connected','INFO',id);return{ok:true,message:'Connected'}},async disconnect(id){snapshot={...snapshot,accounts:snapshot.accounts.map(a=>a.id===id?{...a,state:'DISCONNECTED',tradingEnabled:false}:a)};event('Account disconnected','WARNING',id);return{ok:true,message:'Disconnected'}},async reconnect(id){event('Reconnect and reconciliation completed','INFO',id);return{ok:true,message:'Reconnected and reconciled'}},async testConnection(){await new Promise(r=>setTimeout(r,600));return{ok:true,message:'Terminal reachable • authentication valid • market data available • trade permission detected'}},async setAccountTrading(id,enabled){snapshot={...snapshot,accounts:snapshot.accounts.map(a=>a.id===id?{...a,tradingEnabled:enabled}:a)};event(`Account trading ${enabled?'enabled':'paused'}`,enabled?'INFO':'WARNING',id);return{ok:true,message:'Updated'}},async setGlobalTrading(enabled){snapshot={...snapshot,globalTradingEnabled:enabled};event(`Global new-order execution ${enabled?'enabled':'stopped'}`,enabled?'INFO':'WARNING');return{ok:true,message:'Updated'}},async reconcile(id){event('Broker positions reconciled with Cacsms world model','INFO',id);return{ok:true,message:'Reconciliation complete'}},async emergencyStop(scope){if(scope.accountId)snapshot={...snapshot,accounts:snapshot.accounts.map(a=>a.id===scope.accountId?{...a,tradingEnabled:false}:a)};else snapshot={...snapshot,globalTradingEnabled:false};event('Emergency stop applied to NEW entries only','WARNING',scope.accountId);return{ok:true,message:'New entries stopped; existing positions unchanged'}}}}
