/** Production-facing normalized snapshot. This is the boundary between the autonomous backend and the page. */
export type Lifecycle='NO_OPPORTUNITY'|'WATCHING'|'SETUP_DEVELOPING'|'NEAR_CONFIRMATION'|'CONFIRMATION_PENDING'|'CONFIRMED'|'INVALIDATED'|'EXPIRED'|'COMPLETED';
export type MarketState='TRENDING'|'PULLBACK'|'RANGING'|'COMPRESSION'|'BREAKOUT_DEVELOPING'|'BREAKOUT_CONFIRMED'|'RETEST'|'REVERSAL_DEVELOPING'|'REVERSAL_CONFIRMED'|'EXHAUSTION'|'TRANSITION'|'UNCLEAR';
export type Reconciliation='AGREEMENT'|'PARTIAL'|'CONFLICT'|'INSUFFICIENT_DATA';
export type StepState='COMPLETE'|'ACTIVE'|'PENDING'|'FAILED'|'NOT_REQUIRED';
export interface AutonomousTimeframe{timeframe:'YTD'|'Q'|'MN'|'W'|'D1'|'H8'|'H1'|'M15'|'M5';direction:'BULLISH'|'BEARISH'|'NEUTRAL'|'MIXED';marketState:MarketState;evidenceScore:number|null;closedBarTime:number;structure?:string;channel?:string;supertrend?:string;}
export interface AutonomousEvidence{id:string;kind:'SUPPORTING'|'CONFLICTING'|'MISSING';source:'CHANNEL'|'STRUCTURE'|'SUPERTREND'|'STRENGTH'|'OPPORTUNITY'|'P1P2'|'CONFIRMATION'|'AI';timeframe?:string;text:string;weight?:number;observedAt:number;}
export interface TradabilityStep{id:string;label:string;state:StepState;reason?:string;completedAt?:number;}
export interface AutonomousSnapshot{schemaVersion:1;analysisId:string;symbol:string;createdAt:number;updatedAt:number;primaryTimeframe:string;lifecycle:Lifecycle;marketState:MarketState;direction:'BULLISH'|'BEARISH'|'NEUTRAL'|'MIXED';structure:string;evidenceScore:number|null;primaryThesis:{type:string;title:string;summary:string;invalidationReason:string;};alternativeThesis?:{type:string;title:string;summary:string;activationCondition:string;};timeframes:AutonomousTimeframe[];evidence:AutonomousEvidence[];tradability:TradabilityStep[];reconciliation:Reconciliation;nextExpectedEvent?:string;engineStates:{channel:string;supertrend:string;strength:string;opportunity:string;p1p2:string;confirmation:string;};chart:{candles:Array<{time:number;open:number;high:number;low:number;close:number;volume:number}>;supertrend:Array<{time:number;value:number;direction:'BULLISH'|'BEARISH'}>;channels:Array<{id:string;upper:Array<{time:number;price:number}>;lower:Array<{time:number;price:number}>;median?:Array<{time:number;price:number}>}>;zones:Array<{id:string;kind:'SUPPLY'|'DEMAND'|'ERZ';label:string;from:number;to:number;high:number;low:number}>;annotations:Array<{id:string;kind:'BOS'|'CHOCH'|'SWING_HIGH'|'SWING_LOW'|'P1'|'P2_BREAK'|'REACTION'|'RETEST';time:number;price:number;label:string;priority:number}>;levels:Array<{id:string;kind:'TARGET'|'INVALIDATION'|'ENTRY'|'BREAK';price:number;label:string}>;scenario:Array<{id:string;time:number;price:number;label:string;state:'OBSERVED'|'PROJECTED'}>;};}
